import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

type Language = "en" | "hi" | "te";

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = "agri_lang";

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.brandName": "SprayBot Monitor",
    "app.brandTagline": "Monitoring only",
    "nav.analytics": "Analytics",
    "nav.dashboard": "Dashboard",
    "nav.devices": "Devices",
    "nav.demo": "Demo",
    "nav.reports": "Reports",
    "nav.profile": "Profile",
    "route.dashboard.title": "Pesticide Spraying Bot Dashboard",
    "route.dashboard.subtitle": "Real-Time Monitoring and Data Analytics",
    "route.devices.title": "Connected Devices",
    "route.devices.subtitle": "Monitor multiple spraying bots",
    "route.demo.title": "Demo / Sample Data View",
    "route.demo.subtitle": "Sample data shown before a bot is connected",
    "route.reports.title": "Reports",
    "route.reports.subtitle": "Read-only performance summaries",
    "route.profile.title": "Profile",
    "route.profile.subtitle": "User and monitoring access overview",
    "topbar.notifications": "Notifications",
    "topbar.noNotifications": "No notifications yet",
    "topbar.allAccounts": "All Accounts",
    "topbar.addAccount": "Add Account",
    "topbar.logout": "Log out",
    "topbar.defaultUser": "Agri Monitor User",
    "auth.subtitle": "Secure agricultural telemetry platform",
    "auth.welcomeBack": "Welcome Back",
    "auth.createAccount": "Create New Account",
    "auth.emailAddress": "Email Address",
    "auth.emailPlaceholder": "farmer@agrispray.io",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "••••••••",
    "auth.userName": "User Name",
    "auth.userNamePlaceholder": "e.g. Farmer John",
    "auth.processing": "Processing...",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.toggleToSignup": "Don't have an account? Sign Up",
    "auth.toggleToSignin": "Already have an account? Sign In",
    "auth.authorizedOnly": "Authorized Monitoring Only",
    "auth.legalNotice": "By logging in, you agree to our Terms of Service and Privacy Policy for agricultural data management.",
    "auth.fillFields": "Please fill in all fields",
    "auth.welcomeBackToast": "Welcome back!",
    "auth.accountCreatedToast": "Account created successfully!",
    "auth.hidePassword": "Hide password",
    "auth.showPassword": "Show password",
    "language.label": "Language",
    "status.active": "Active",
    "status.offline": "Offline",
    "status.error": "Error",
    "status.connected": "Connected",
    "status.connecting": "Connecting",
    "status.disconnected": "Disconnected",
    "status.readOnly": "Read-Only",
    "status.ready": "Ready",
    "status.strongSignal": "Strong",
    "status.loading": "Loading",
    "status.unknown": "Unknown",
    "common.none": "None",
    "unit.meters": "meters",
    "unit.acres": "acres",
    "unit.liters": "liters",
    "alerts.lowBattery": "Low Battery Warning",
    "logs.statusInfo": "Info",
    "logs.statusSuccess": "Success",
    "logs.statusWarn": "Warning",
    "logs.statusError": "Error",
    "button.back": "Back",
    "button.connectDevice": "Connect a Device",
    "button.connectMore": "Connect More",
    "button.disconnect": "Disconnect",
    "button.rescanNetwork": "Rescan Network",
    "button.scanAgain": "Scan Again",
    "button.validateConnect": "Validate & Connect",
    "button.validating": "Validating...",
    "button.export": "Export",
    "button.viewDashboard": "View Dashboard",
    "button.goToDashboard": "Go to Dashboard to Connect",
    "button.exportAnalytics": "Export Analytics",
    "button.thingSpeakSetup": "ThingSpeak Setup",
    "dashboard.noDevicesTitle": "No Devices Connected",
    "dashboard.noDevicesDesc": "Start by connecting your first pesticide spraying bot to monitor its live telemetry and field performance.",
    "dashboard.fetchConnectedError": "Failed to fetch connected devices",
    "dashboard.selectDeviceTitle": "Select a Connected Device",
    "dashboard.selectDeviceDesc": "Choose a bot to view its live dashboard, or connect a new device.",
    "dashboard.connectedBots": "Connected Bots",
    "dashboard.liveMonitoring": "Live Monitoring Dashboard",
    "dashboard.botInsights": "Bot Monitoring Insights",
    "dashboard.deviceDisconnectedTitle": "Device Disconnected",
    "dashboard.deviceDisconnectedDesc": "Real-time monitoring has been suspended.",
    "dashboard.botStatus": "Bot Status",
    "dashboard.currentState": "Current State",
    "dashboard.batteryLevel": "Battery Level",
    "dashboard.tankLevel": "Pesticide Tank Level",
    "dashboard.liveProgress": "Live Progress",
    "dashboard.distanceTrend": "Distance Traveled Trend (meters)",
    "dashboard.realTimeChart": "Real-time Trend Chart",
    "dashboard.collectingPathData": "Collecting path data from {botId}...",
    "dashboard.resourceAllocation": "Resource Allocation",
    "dashboard.litersPerSession": "Liters sprayed per session time",
    "dashboard.resourceChart": "Resource Allocation Chart",
    "dashboard.measuringDistribution": "Measuring pesticide distribution efficiency...",
    "dashboard.activityLogs": "Activity Logs",
    "dashboard.latestRecords": "Latest monitoring records",
    "dashboard.noLogsTitle": "No recent logs from {botId}",
    "dashboard.noLogsDesc": "Logs will appear here once the bot starts its mission.",
    "metric.distanceTraveled": "Distance Traveled",
    "metric.areaCovered": "Area Covered",
    "metric.pesticideSprayed": "Pesticide Sprayed",
    "metric.operatingTime": "Operating Time",
    "metric.fieldCoverage": "Field coverage",
    "metric.measuredTankOutput": "Measured tank output",
    "metric.recordedActiveDuration": "Recorded active duration",
    "metric.totalDistance": "{botId} total distance",
    "devices.fetchError": "Failed to fetch registered bots",
    "devices.emptyTitle": "No Devices Connected",
    "devices.emptyDesc": "Your device registry is currently empty. Please connect a bot from the dashboard to start monitoring.",
    "devices.title": "Connected Devices",
    "devices.subtitle": "View all pesticide spraying bots connected for monitoring and analytics.",
    "devices.multipleMonitoring": "Multiple bot monitoring",
    "devices.readOnlyList": "Read-only device list",
    "devices.active": "Active",
    "devices.offline": "Offline",
    "devices.connectedHwId": "Connected HW ID",
    "demo.noBotsTitle": "No Demo Bots Available",
    "demo.noBotsDesc": "Add demo bot data to preview the dashboard layout.",
    "demo.demoBots": "Demo Bots",
    "demo.demoMode": "Demo mode",
    "demo.demoModeDesc": "No connected device to disconnect.",
    "connect.fetchError": "Failed to fetch available bots",
    "connect.devicePairing": "Device Pairing",
    "connect.liveScanning": "Live Scanning",
    "connect.botDiscovery": "Bot Discovery",
    "connect.searchingDesc": "Searching for real ESP32-powered spraying bots on your local network.",
    "connect.scanningTitle": "Scanning Wi-Fi for bots...",
    "connect.scanningDesc": "Ensuring your ESP32 Wi-Fi module is powered on and connected to the same network as this dashboard.",
    "connect.availableNearby": "Available Nearby Devices",
    "connect.rescanNetwork": "Rescan Network",
    "connect.hardwareId": "Hardware ID: {botId}",
    "connect.signal": "Signal",
    "connect.esp32Ready": "ESP32 Ready",
    "connect.connectNow": "Connect Now",
    "connect.noBotsTitle": "No Real Bots Found",
    "connect.noBotsDesc": "We couldn't detect any ESP32 modules on your network. Check your Wi-Fi settings and try again.",
    "connect.cantFindBot": "Can't find your bot?",
    "connect.manualDesc": "Enter your device details to validate and connect using real telemetry.",
    "connect.botId": "Bot ID",
    "connect.botNameOptional": "Bot Name (optional)",
    "connect.channelId": "Channel ID",
    "connect.readApiKey": "Read API Key",
    "connect.botIdPlaceholder": "Enter bot ID",
    "connect.botNamePlaceholder": "e.g. Orchard Unit",
    "connect.channelPlaceholder": "ThingSpeak Channel ID",
    "connect.readKeyPlaceholder": "ThingSpeak Read API Key",
    "connect.validating": "Validating...",
    "connect.validateConnect": "Validate & Connect",
    "connect.thingSpeakSetup": "ThingSpeak Setup",
    "connect.connectingToast": "Connecting to {botId}...",
    "connect.connectingDesc": "Establishing secure agricultural telemetry link.",
    "connect.syncedToast": "{botId} is now synchronized.",
    "connect.missingFields": "Please enter Bot ID, Channel ID, and Read API Key",
    "connect.validationFailed": "Validation failed",
    "connect.connectionFailed": "Connection failed",
    "connect.invalidChannel": "Invalid Channel ID or Read API Key",
    "connect.noTelemetry": "No telemetry found for this channel",
    "reports.fetchError": "Failed to fetch historical reports",
    "reports.noReportsTitle": "No Reports Available",
    "reports.noReportsDesc": "Historical analytics will appear here once your bot completes its first spraying mission.",
    "reports.performanceReports": "Performance Reports",
    "reports.connected": "Connected",
    "reports.disconnected": "Disconnected",
    "reports.operationAnalytics": "Operation Analytics",
    "reports.operationDesc": "Historical performance data and resource efficiency metrics.",
    "reports.connectedBot": "Connected Bot: {botId}",
    "reports.exportSoon": "PDF Exporting is coming soon.",
    "reports.totalDistance": "Total Distance",
    "reports.totalArea": "Total Area",
    "reports.pesticideUsed": "Pesticide Used",
    "reports.lastActive": "Last Active",
    "reports.historicalPerformance": "Historical Performance",
    "reports.resourceUtilization": "Resource Utilization",
    "reports.performanceInsights": "Performance Insights",
    "reports.insightData": "Analytics are based on real-time data received from {botId}. Insights will be generated as more data points are collected.",
    "reports.insightEfficiency": "Current session coverage shows a resource efficiency of {percent}% compared to regional standards.",
    "profile.nameEmpty": "Name cannot be empty",
    "profile.updated": "Profile updated!",
    "profile.botOwnerProfile": "Bot Owner Profile",
    "profile.subtitle": "Personalized monitoring access for your pesticide spraying fleet.",
    "profile.totalConnectedDevices": "Total Connected Devices",
    "profile.monitoringAccess": "Monitoring Access",
    "profile.readOnly": "Read Only",
    "profile.oneBot": "1 Bot",
    "profile.zeroBots": "0 Bots",
    "profile.recentActivity": "Recent Device Activity",
    "profile.monitoringRecords": "Monitoring records",
    "profile.deviceId": "Device ID",
    "profile.lastActiveTime": "Last Active Time",
    "profile.status": "Status",
    "profile.battery": "Battery",
    "profile.tank": "Tank",
    "profile.loadingTelemetry": "Loading telemetry...",
    "profile.noTelemetry": "No telemetry available yet.",
    "profile.noActivityTitle": "No Bot Activity Recorded",
    "profile.noActivityDesc": "Connect a device to see historical telemetry logs.",
    "logs.fetchError": "Failed to fetch monitoring logs",
    "logs.searchPlaceholder": "Search monitoring logs…",
    "logs.eventType": "Event type",
    "logs.allEvents": "All events",
    "logs.telemetry": "Telemetry",
    "logs.task": "Task",
    "logs.tank": "Tank",
    "logs.device": "Device",
    "logs.exportSuccess": "Monitoring logs exported as CSV",
    "logs.timestamp": "Timestamp",
    "logs.event": "Event",
    "logs.detail": "Detail",
    "logs.status": "Status",
    "logs.loading": "Loading logs...",
    "logs.noLogs": "No monitoring logs available.",
    "logs.connectDevice": "Connect a device to view logs.",
    "logs.deviceAlert": "Device Alert",
    "logs.batteryWarning": "Battery Warning",
    "logs.tankWarning": "Tank Warning",
    "logs.telemetryUpdate": "Telemetry Update",
    "logs.detailDistance": "Distance {value} m",
    "logs.detailArea": "Area {value} acres",
    "logs.detailTank": "Tank {value}%",
    "logs.detailBattery": "Battery {value}%",
    "logs.detailReceived": "Telemetry received",
    "notFound.title": "Oops! Page not found",
    "notFound.returnHome": "Return to Home",
    "help.title": "Need Help?",
    "help.desc": "Having trouble with your bot? Send us a message and we will call you back.",
    "help.phone": "Your Phone Number",
    "help.phonePlaceholder": "Enter your phone number",
    "help.message": "Your Message",
    "help.messagePlaceholder": "Describe your problem...",
    "help.submit": "Send Help Request",
    "help.sent": "Help request sent! We will call you soon.",
    "help.failed": "Failed to send request",
  },
  hi: {
    "app.brandName": "SprayBot Monitor",
    "app.brandTagline": "केवल मॉनिटरिंग",
    "nav.analytics": "विश्लेषण",
    "nav.dashboard": "डैशबोर्ड",
    "nav.devices": "डिवाइस",
    "nav.demo": "डेमो",
    "nav.reports": "रिपोर्ट्स",
    "nav.profile": "प्रोफ़ाइल",
    "route.dashboard.title": "कीटनाशक छिड़काव बॉट डैशबोर्ड",
    "route.dashboard.subtitle": "रीयल-टाइम मॉनिटरिंग और डेटा एनालिटिक्स",
    "route.devices.title": "कनेक्टेड डिवाइस",
    "route.devices.subtitle": "कई छिड़काव बॉट्स की निगरानी",
    "route.demo.title": "डेमो / सैंपल डेटा दृश्य",
    "route.demo.subtitle": "बॉट कनेक्ट होने से पहले दिखा सैंपल डेटा",
    "route.reports.title": "रिपोर्ट्स",
    "route.reports.subtitle": "केवल पढ़ने योग्य प्रदर्शन सारांश",
    "route.profile.title": "प्रोफ़ाइल",
    "route.profile.subtitle": "उपयोगकर्ता और मॉनिटरिंग एक्सेस अवलोकन",
    "topbar.notifications": "सूचनाएँ",
    "topbar.noNotifications": "अभी कोई सूचनाएँ नहीं",
    "topbar.allAccounts": "सभी खाते",
    "topbar.addAccount": "खाता जोड़ें",
    "topbar.logout": "लॉग आउट",
    "topbar.defaultUser": "एग्री मॉनिटर उपयोगकर्ता",
    "auth.subtitle": "सुरक्षित कृषि टेलीमेट्री प्लेटफ़ॉर्म",
    "auth.welcomeBack": "वापसी पर स्वागत है",
    "auth.createAccount": "नया खाता बनाएं",
    "auth.emailAddress": "ईमेल पता",
    "auth.emailPlaceholder": "farmer@agrispray.io",
    "auth.password": "पासवर्ड",
    "auth.passwordPlaceholder": "••••••••",
    "auth.userName": "उपयोगकर्ता नाम",
    "auth.userNamePlaceholder": "उदा. किसान जॉन",
    "auth.processing": "प्रोसेस हो रहा है...",
    "auth.signIn": "साइन इन",
    "auth.signUp": "साइन अप",
    "auth.toggleToSignup": "खाता नहीं है? साइन अप करें",
    "auth.toggleToSignin": "पहले से खाता है? साइन इन करें",
    "auth.authorizedOnly": "केवल अधिकृत मॉनिटरिंग",
    "auth.legalNotice": "लॉग इन करके आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं, जो कृषि डेटा प्रबंधन के लिए है।",
    "auth.fillFields": "कृपया सभी फ़ील्ड भरें",
    "auth.welcomeBackToast": "वापसी पर स्वागत है!",
    "auth.accountCreatedToast": "खाता सफलतापूर्वक बनाया गया!",
    "auth.hidePassword": "पासवर्ड छिपाएँ",
    "auth.showPassword": "पासवर्ड दिखाएँ",
    "language.label": "भाषा",
    "status.active": "सक्रिय",
    "status.offline": "ऑफ़लाइन",
    "status.error": "त्रुटि",
    "status.connected": "कनेक्टेड",
    "status.connecting": "कनेक्ट हो रहा है",
    "status.disconnected": "डिसकनेक्टेड",
    "status.readOnly": "केवल पढ़ने योग्य",
    "status.ready": "तैयार",
    "status.strongSignal": "मज़बूत",
    "status.loading": "लोड हो रहा है",
    "status.unknown": "अज्ञात",
    "common.none": "कोई नहीं",
    "unit.meters": "मीटर",
    "unit.acres": "एकड़",
    "unit.liters": "लीटर",
    "alerts.lowBattery": "कम बैटरी चेतावनी",
    "logs.statusInfo": "सूचना",
    "logs.statusSuccess": "सफल",
    "logs.statusWarn": "चेतावनी",
    "logs.statusError": "त्रुटि",
    "button.back": "वापस",
    "button.connectDevice": "डिवाइस कनेक्ट करें",
    "button.connectMore": "और कनेक्ट करें",
    "button.disconnect": "डिसकनेक्ट",
    "button.rescanNetwork": "नेटवर्क फिर से स्कैन करें",
    "button.scanAgain": "फिर से स्कैन करें",
    "button.validateConnect": "सत्यापित करें और कनेक्ट करें",
    "button.validating": "सत्यापित हो रहा है...",
    "button.export": "एक्सपोर्ट",
    "button.viewDashboard": "डैशबोर्ड देखें",
    "button.goToDashboard": "कनेक्ट करने के लिए डैशबोर्ड पर जाएं",
    "button.exportAnalytics": "एनालिटिक्स एक्सपोर्ट करें",
    "button.thingSpeakSetup": "ThingSpeak सेटअप",
    "dashboard.noDevicesTitle": "कोई डिवाइस कनेक्ट नहीं है",
    "dashboard.noDevicesDesc": "लाइव टेलीमेट्री और फील्ड प्रदर्शन देखने के लिए अपना पहला कीटनाशक छिड़काव बॉट कनेक्ट करें।",
    "dashboard.fetchConnectedError": "कनेक्टेड डिवाइस लाने में विफल",
    "dashboard.selectDeviceTitle": "कनेक्टेड डिवाइस चुनें",
    "dashboard.selectDeviceDesc": "लाइव डैशबोर्ड देखने के लिए एक बॉट चुनें, या नया डिवाइस कनेक्ट करें।",
    "dashboard.connectedBots": "कनेक्टेड बॉट्स",
    "dashboard.liveMonitoring": "लाइव मॉनिटरिंग डैशबोर्ड",
    "dashboard.botInsights": "बॉट मॉनिटरिंग इनसाइट्स",
    "dashboard.deviceDisconnectedTitle": "डिवाइस डिसकनेक्टेड",
    "dashboard.deviceDisconnectedDesc": "रीयल-टाइम मॉनिटरिंग अस्थायी रूप से रोकी गई है।",
    "dashboard.botStatus": "बॉट स्थिति",
    "dashboard.currentState": "वर्तमान स्थिति",
    "dashboard.batteryLevel": "बैटरी स्तर",
    "dashboard.tankLevel": "कीटनाशक टैंक स्तर",
    "dashboard.liveProgress": "लाइव प्रगति",
    "dashboard.distanceTrend": "दूरी ट्रेंड (मीटर)",
    "dashboard.realTimeChart": "रीयल-टाइम ट्रेंड चार्ट",
    "dashboard.collectingPathData": "{botId} से पाथ डेटा एकत्र किया जा रहा है...",
    "dashboard.resourceAllocation": "संसाधन आवंटन",
    "dashboard.litersPerSession": "सत्र समय के अनुसार छिड़के गए लीटर",
    "dashboard.resourceChart": "संसाधन आवंटन चार्ट",
    "dashboard.measuringDistribution": "कीटनाशक वितरण दक्षता मापी जा रही है...",
    "dashboard.activityLogs": "गतिविधि लॉग्स",
    "dashboard.latestRecords": "नवीनतम मॉनिटरिंग रिकॉर्ड",
    "dashboard.noLogsTitle": "{botId} से कोई हालिया लॉग नहीं",
    "dashboard.noLogsDesc": "बॉट के मिशन शुरू करने पर लॉग यहाँ दिखेंगे।",
    "metric.distanceTraveled": "दूरी तय की गई",
    "metric.areaCovered": "कवर किया गया क्षेत्र",
    "metric.pesticideSprayed": "छिड़का गया कीटनाशक",
    "metric.operatingTime": "संचालन समय",
    "metric.fieldCoverage": "फील्ड कवरेज",
    "metric.measuredTankOutput": "मापा गया टैंक आउटपुट",
    "metric.recordedActiveDuration": "रिकॉर्ड किया गया सक्रिय समय",
    "metric.totalDistance": "{botId} कुल दूरी",
    "devices.fetchError": "रजिस्टर्ड बॉट्स लाने में विफल",
    "devices.emptyTitle": "कोई डिवाइस कनेक्ट नहीं है",
    "devices.emptyDesc": "आपकी डिवाइस रजिस्ट्री अभी खाली है। मॉनिटरिंग शुरू करने के लिए डैशबोर्ड से बॉट कनेक्ट करें।",
    "devices.title": "कनेक्टेड डिवाइस",
    "devices.subtitle": "मॉनिटरिंग और एनालिटिक्स के लिए जुड़े सभी कीटनाशक स्प्रे बॉट्स देखें।",
    "devices.multipleMonitoring": "मल्टी-बॉट मॉनिटरिंग",
    "devices.readOnlyList": "केवल पढ़ने योग्य डिवाइस सूची",
    "devices.active": "सक्रिय",
    "devices.offline": "ऑफ़लाइन",
    "devices.connectedHwId": "कनेक्टेड HW ID",
    "demo.noBotsTitle": "कोई डेमो बॉट उपलब्ध नहीं",
    "demo.noBotsDesc": "डैशबोर्ड लेआउट देखने के लिए डेमो बॉट डेटा जोड़ें।",
    "demo.demoBots": "डेमो बॉट्स",
    "demo.demoMode": "डेमो मोड",
    "demo.demoModeDesc": "डिसकनेक्ट करने के लिए कोई डिवाइस कनेक्ट नहीं है।",
    "connect.fetchError": "उपलब्ध बॉट्स लाने में विफल",
    "connect.devicePairing": "डिवाइस पेयरिंग",
    "connect.liveScanning": "लाइव स्कैनिंग",
    "connect.botDiscovery": "बॉट डिस्कवरी",
    "connect.searchingDesc": "आपके लोकल नेटवर्क पर वास्तविक ESP32-संचालित स्प्रे बॉट्स खोजे जा रहे हैं।",
    "connect.scanningTitle": "Wi-Fi पर बॉट्स स्कैन हो रहे हैं...",
    "connect.scanningDesc": "सुनिश्चित करें कि आपका ESP32 Wi-Fi मॉड्यूल चालू है और इसी नेटवर्क से जुड़ा है।",
    "connect.availableNearby": "पास के उपलब्ध डिवाइस",
    "connect.rescanNetwork": "नेटवर्क फिर से स्कैन करें",
    "connect.hardwareId": "हार्डवेयर ID: {botId}",
    "connect.signal": "सिग्नल",
    "connect.esp32Ready": "ESP32 तैयार",
    "connect.connectNow": "अभी कनेक्ट करें",
    "connect.noBotsTitle": "कोई वास्तविक बॉट नहीं मिला",
    "connect.noBotsDesc": "हम आपके नेटवर्क पर कोई ESP32 मॉड्यूल नहीं ढूंढ पाए। Wi-Fi सेटिंग्स जांचें और फिर कोशिश करें।",
    "connect.cantFindBot": "अपना बॉट नहीं मिल रहा?",
    "connect.manualDesc": "रीयल टेलीमेट्री का उपयोग करके सत्यापित और कनेक्ट करने के लिए डिवाइस विवरण दर्ज करें।",
    "connect.botId": "बॉट ID",
    "connect.botNameOptional": "बॉट नाम (वैकल्पिक)",
    "connect.channelId": "चैनल ID",
    "connect.readApiKey": "रीड API की",
    "connect.botIdPlaceholder": "बॉट ID दर्ज करें",
    "connect.botNamePlaceholder": "उदा. Orchard Unit",
    "connect.channelPlaceholder": "ThingSpeak चैनल ID",
    "connect.readKeyPlaceholder": "ThingSpeak Read API Key",
    "connect.validating": "सत्यापित हो रहा है...",
    "connect.validateConnect": "सत्यापित करें और कनेक्ट करें",
    "connect.thingSpeakSetup": "ThingSpeak सेटअप",
    "connect.connectingToast": "{botId} से कनेक्ट हो रहा है...",
    "connect.connectingDesc": "सुरक्षित कृषि टेलीमेट्री लिंक स्थापित हो रहा है।",
    "connect.syncedToast": "{botId} अब सिंक्रोनाइज़ हो गया है।",
    "connect.missingFields": "कृपया Bot ID, Channel ID, और Read API Key दर्ज करें",
    "connect.validationFailed": "सत्यापन असफल",
    "connect.connectionFailed": "कनेक्शन विफल",
    "connect.invalidChannel": "अमान्य चैनल ID या रीड API की",
    "connect.noTelemetry": "इस चैनल के लिए कोई टेलीमेट्री नहीं मिली",
    "reports.fetchError": "ऐतिहासिक रिपोर्ट्स लाने में विफल",
    "reports.noReportsTitle": "कोई रिपोर्ट उपलब्ध नहीं",
    "reports.noReportsDesc": "बॉट का पहला छिड़काव मिशन पूरा होने पर ऐतिहासिक एनालिटिक्स यहां दिखेंगे।",
    "reports.performanceReports": "परफॉर्मेंस रिपोर्ट्स",
    "reports.connected": "कनेक्टेड",
    "reports.disconnected": "डिसकनेक्टेड",
    "reports.operationAnalytics": "ऑपरेशन एनालिटिक्स",
    "reports.operationDesc": "ऐतिहासिक प्रदर्शन डेटा और संसाधन दक्षता मेट्रिक्स।",
    "reports.connectedBot": "कनेक्टेड बॉट: {botId}",
    "reports.exportSoon": "PDF एक्सपोर्ट जल्द आ रहा है।",
    "reports.totalDistance": "कुल दूरी",
    "reports.totalArea": "कुल क्षेत्र",
    "reports.pesticideUsed": "उपयोग किया गया कीटनाशक",
    "reports.lastActive": "आखिरी सक्रिय",
    "reports.historicalPerformance": "ऐतिहासिक प्रदर्शन",
    "reports.resourceUtilization": "संसाधन उपयोग",
    "reports.performanceInsights": "परफॉर्मेंस इनसाइट्स",
    "reports.insightData": "एनालिटिक्स {botId} से प्राप्त रीयल-टाइम डेटा पर आधारित है। जैसे-जैसे डेटा बढ़ेगा, इनसाइट्स जेनरेट होंगे।",
    "reports.insightEfficiency": "वर्तमान सत्र का कवरेज क्षेत्रीय मानकों की तुलना में {percent}% संसाधन दक्षता दिखाता है।",
    "profile.nameEmpty": "नाम खाली नहीं हो सकता",
    "profile.updated": "प्रोफ़ाइल अपडेट हो गई!",
    "profile.botOwnerProfile": "बॉट ओनर प्रोफ़ाइल",
    "profile.subtitle": "आपके कीटनाशक छिड़काव फ्लीट के लिए व्यक्तिगत मॉनिटरिंग एक्सेस।",
    "profile.totalConnectedDevices": "कुल कनेक्टेड डिवाइस",
    "profile.monitoringAccess": "मॉनिटरिंग एक्सेस",
    "profile.readOnly": "केवल पढ़ने योग्य",
    "profile.oneBot": "1 बॉट",
    "profile.zeroBots": "0 बॉट्स",
    "profile.recentActivity": "हाल की डिवाइस गतिविधि",
    "profile.monitoringRecords": "मॉनिटरिंग रिकॉर्ड",
    "profile.deviceId": "डिवाइस ID",
    "profile.lastActiveTime": "अंतिम सक्रिय समय",
    "profile.status": "स्थिति",
    "profile.battery": "बैटरी",
    "profile.tank": "टैंक",
    "profile.loadingTelemetry": "टेलीमेट्री लोड हो रही है...",
    "profile.noTelemetry": "अभी कोई टेलीमेट्री उपलब्ध नहीं।",
    "profile.noActivityTitle": "कोई बॉट गतिविधि रिकॉर्ड नहीं",
    "profile.noActivityDesc": "ऐतिहासिक टेलीमेट्री लॉग देखने के लिए डिवाइस कनेक्ट करें।",
    "logs.fetchError": "मॉनिटरिंग लॉग्स लाने में विफल",
    "logs.searchPlaceholder": "मॉनिटरिंग लॉग्स खोजें…",
    "logs.eventType": "इवेंट प्रकार",
    "logs.allEvents": "सभी इवेंट",
    "logs.telemetry": "टेलीमेट्री",
    "logs.task": "कार्य",
    "logs.tank": "टैंक",
    "logs.device": "डिवाइस",
    "logs.exportSuccess": "मॉनिटरिंग लॉग्स CSV में एक्सपोर्ट हो गए",
    "logs.timestamp": "टाइमस्टैम्प",
    "logs.event": "इवेंट",
    "logs.detail": "विवरण",
    "logs.status": "स्थिति",
    "logs.loading": "लॉग्स लोड हो रहे हैं...",
    "logs.noLogs": "कोई मॉनिटरिंग लॉग उपलब्ध नहीं।",
    "logs.connectDevice": "लॉग देखने के लिए डिवाइस कनेक्ट करें।",
    "logs.deviceAlert": "डिवाइस अलर्ट",
    "logs.batteryWarning": "बैटरी चेतावनी",
    "logs.tankWarning": "टैंक चेतावनी",
    "logs.telemetryUpdate": "टेलीमेट्री अपडेट",
    "logs.detailDistance": "दूरी {value} m",
    "logs.detailArea": "क्षेत्र {value} acres",
    "logs.detailTank": "टैंक {value}%",
    "logs.detailBattery": "बैटरी {value}%",
    "logs.detailReceived": "टेलीमेट्री प्राप्त हुई",
    "notFound.title": "ओह! पेज नहीं मिला",
    "notFound.returnHome": "होम पर लौटें",
    "help.title": "मदद चाहिए?",
    "help.desc": "अपने बॉट में कोई समस्या है? हमें संदेश भेजें और हम आपको वापस कॉल करेंगे।",
    "help.phone": "आपका फ़ोन नंबर",
    "help.phonePlaceholder": "अपना फ़ोन नंबर दर्ज करें",
    "help.message": "आपका संदेश",
    "help.messagePlaceholder": "अपनी समस्या बताएं...",
    "help.submit": "सहायता अनुरोध भेजें",
    "help.sent": "सहायता अनुरोध भेज दिया गया! हम जल्द ही आपको कॉल करेंगे।",
    "help.failed": "अनुरोध भेजने में विफल",
  },
  te: {
    "app.brandName": "SprayBot Monitor",
    "app.brandTagline": "మానిటరింగ్ మాత్రమే",
    "nav.analytics": "విశ్లేషణ",
    "nav.dashboard": "డాష్‌బోర్డ్",
    "nav.devices": "పరికరాలు",
    "nav.demo": "డెమో",
    "nav.reports": "రిపోర్ట్స్",
    "nav.profile": "ప్రొఫైల్",
    "route.dashboard.title": "పెస్టిసైడ్ స్ప్రేయింగ్ బాట్ డాష్‌బోర్డ్",
    "route.dashboard.subtitle": "రియల్-టైమ్ మానిటరింగ్ మరియు డేటా అనలిటిక్స్",
    "route.devices.title": "కనెక్ట్ చేసిన పరికరాలు",
    "route.devices.subtitle": "బహుళ స్ప్రేయింగ్ బాట్స్‌ను మానిటర్ చేయండి",
    "route.demo.title": "డెమో / నమూనా డేటా వీక్షణ",
    "route.demo.subtitle": "బాట్ కనెక్ట్ చేయకముందు చూపించే నమూనా డేటా",
    "route.reports.title": "రిపోర్ట్స్",
    "route.reports.subtitle": "కేవలం చదవగల పనితీరు సంగ్రహాలు",
    "route.profile.title": "ప్రొఫైల్",
    "route.profile.subtitle": "యూజర్ మరియు మానిటరింగ్ యాక్సెస్ అవలోకనం",
    "topbar.notifications": "నోటిఫికేషన్లు",
    "topbar.noNotifications": "ఇప్పటివరకు నోటిఫికేషన్లు లేవు",
    "topbar.allAccounts": "అన్ని ఖాతాలు",
    "topbar.addAccount": "ఖాతాను జోడించండి",
    "topbar.logout": "లాగ్ అవుట్",
    "topbar.defaultUser": "అగ్రి మానిటర్ వినియోగదారు",
    "auth.subtitle": "సురక్షిత వ్యవసాయ టెలిమెట్రీ ప్లాట్‌ఫారమ్",
    "auth.welcomeBack": "మళ్లీ స్వాగతం",
    "auth.createAccount": "కొత్త ఖాతా సృష్టించండి",
    "auth.emailAddress": "ఇమెయిల్ చిరునామా",
    "auth.emailPlaceholder": "farmer@agrispray.io",
    "auth.password": "పాస్‌వర్డ్",
    "auth.passwordPlaceholder": "••••••••",
    "auth.userName": "వినియోగదారు పేరు",
    "auth.userNamePlaceholder": "ఉదా. ఫార్మర్ జాన్",
    "auth.processing": "ప్రాసెస్ అవుతోంది...",
    "auth.signIn": "సైన్ ఇన్",
    "auth.signUp": "సైన్ అప్",
    "auth.toggleToSignup": "ఖాతా లేదా? సైన్ అప్ చేయండి",
    "auth.toggleToSignin": "ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి",
    "auth.authorizedOnly": "అధికారిక మానిటరింగ్ మాత్రమే",
    "auth.legalNotice": "లాగిన్ కావడంతో, వ్యవసాయ డేటా నిర్వహణకు సంబంధించిన మా సేవా నిబంధనలు మరియు గోప్యతా విధానాన్ని మీరు అంగీకరిస్తారు.",
    "auth.fillFields": "దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి",
    "auth.welcomeBackToast": "మళ్లీ స్వాగతం!",
    "auth.accountCreatedToast": "ఖాతా విజయవంతంగా సృష్టించబడింది!",
    "auth.hidePassword": "పాస్‌వర్డ్ దాచండి",
    "auth.showPassword": "పాస్‌వర్డ్ చూపించండి",
    "language.label": "భాష",
    "status.active": "సక్రియ",
    "status.offline": "ఆఫ్‌లైన్",
    "status.error": "లోపం",
    "status.connected": "కనెక్ట్ అయింది",
    "status.connecting": "కనెక్ట్ అవుతోంది",
    "status.disconnected": "డిస్కనెక్ట్ అయింది",
    "status.readOnly": "చదవడానికి మాత్రమే",
    "status.ready": "సిద్ధం",
    "status.strongSignal": "బలమైన",
    "status.loading": "లోడ్ అవుతోంది",
    "status.unknown": "తెలియదు",
    "common.none": "ఏదీ లేదు",
    "unit.meters": "మీటర్లు",
    "unit.acres": "ఎకరాలు",
    "unit.liters": "లీటర్లు",
    "alerts.lowBattery": "తక్కువ బ్యాటరీ హెచ్చరిక",
    "logs.statusInfo": "సమాచారం",
    "logs.statusSuccess": "విజయం",
    "logs.statusWarn": "హెచ్చరిక",
    "logs.statusError": "లోపం",
    "button.back": "వెనక్కి",
    "button.connectDevice": "డివైస్ కనెక్ట్ చేయండి",
    "button.connectMore": "ఇంకా కనెక్ట్ చేయండి",
    "button.disconnect": "డిస్కనెక్ట్",
    "button.rescanNetwork": "నెట్‌వర్క్ మళ్లీ స్కాన్ చేయండి",
    "button.scanAgain": "మళ్లీ స్కాన్ చేయండి",
    "button.validateConnect": "ధృవీకరించి కనెక్ట్ చేయండి",
    "button.validating": "ధృవీకరిస్తోంది...",
    "button.export": "ఎగుమతి",
    "button.viewDashboard": "డాష్‌బోర్డ్ చూడండి",
    "button.goToDashboard": "కనెక్ట్ చేయడానికి డాష్‌బోర్డ్‌కు వెళ్లండి",
    "button.exportAnalytics": "అనలిటిక్స్ ఎగుమతి",
    "button.thingSpeakSetup": "ThingSpeak సెటప్",
    "dashboard.noDevicesTitle": "డివైసులు కనెక్ట్ కాలేదు",
    "dashboard.noDevicesDesc": "లైవ్ టెలిమెట్రీ మరియు ఫీల్డ్ పనితీరు చూడడానికి మీ మొదటి పెస్టిసైడ్ స్ప్రేయింగ్ బాట్‌ను కనెక్ట్ చేయండి.",
    "dashboard.fetchConnectedError": "కనెక్ట్ అయిన డివైసులను తీసుకురాలేకపోయాం",
    "dashboard.selectDeviceTitle": "కనెక్ట్ అయిన డివైస్‌ను ఎంచుకోండి",
    "dashboard.selectDeviceDesc": "లైవ్ డాష్‌బోర్డ్ చూడడానికి బాట్‌ను ఎంచుకోండి లేదా కొత్త డివైస్ కనెక్ట్ చేయండి.",
    "dashboard.connectedBots": "కనెక్ట్ అయిన బాట్స్",
    "dashboard.liveMonitoring": "లైవ్ మానిటరింగ్ డాష్‌బోర్డ్",
    "dashboard.botInsights": "బాట్ మానిటరింగ్ ఇన్‌సైట్స్",
    "dashboard.deviceDisconnectedTitle": "డివైస్ డిస్కనెక్ట్ అయింది",
    "dashboard.deviceDisconnectedDesc": "రియల్-టైమ్ మానిటరింగ్ తాత్కాలికంగా నిలిపివేయబడింది.",
    "dashboard.botStatus": "బాట్ స్థితి",
    "dashboard.currentState": "ప్రస్తుత స్థితి",
    "dashboard.batteryLevel": "బ్యాటరీ స్థాయి",
    "dashboard.tankLevel": "పెస్టిసైడ్ ట్యాంక్ స్థాయి",
    "dashboard.liveProgress": "లైవ్ పురోగతి",
    "dashboard.distanceTrend": "దూరం ట్రెండ్ (మీటర్లు)",
    "dashboard.realTimeChart": "రియల్-టైమ్ ట్రెండ్ చార్ట్",
    "dashboard.collectingPathData": "{botId} నుండి మార్గ డేటా సేకరిస్తోంది...",
    "dashboard.resourceAllocation": "వనరుల కేటాయింపు",
    "dashboard.litersPerSession": "సెషన్ సమయానికి స్ప్రే చేసిన లీటర్లు",
    "dashboard.resourceChart": "వనరుల కేటాయింపు చార్ట్",
    "dashboard.measuringDistribution": "పెస్టిసైడ్ పంపిణీ సామర్థ్యాన్ని కొలుస్తోంది...",
    "dashboard.activityLogs": "కార్యకలాప లాగ్స్",
    "dashboard.latestRecords": "తాజా మానిటరింగ్ రికార్డులు",
    "dashboard.noLogsTitle": "{botId} నుండి తాజా లాగ్స్ లేవు",
    "dashboard.noLogsDesc": "బాట్ మిషన్ ప్రారంభించిన తర్వాత లాగ్స్ ఇక్కడ కనిపిస్తాయి.",
    "metric.distanceTraveled": "దూరం ప్రయాణం",
    "metric.areaCovered": "కవర్ చేసిన ప్రాంతం",
    "metric.pesticideSprayed": "స్ప్రే చేసిన పెస్టిసైడ్",
    "metric.operatingTime": "ఆపరేటింగ్ సమయం",
    "metric.fieldCoverage": "ఫీల్డ్ కవరేజ్",
    "metric.measuredTankOutput": "కొలిచిన ట్యాంక్ అవుట్‌పుట్",
    "metric.recordedActiveDuration": "రికార్డ్ చేసిన యాక్టివ్ సమయం",
    "metric.totalDistance": "{botId} మొత్తం దూరం",
    "devices.fetchError": "రిజిస్టర్ చేసిన బాట్స్‌ను తీసుకురాలేకపోయాం",
    "devices.emptyTitle": "డివైసులు కనెక్ట్ కాలేదు",
    "devices.emptyDesc": "మీ డివైస్ రిజిస్ట్రీ ఖాళీగా ఉంది. మానిటరింగ్ ప్రారంభించడానికి డాష్‌బోర్డ్ నుండి బాట్‌ను కనెక్ట్ చేయండి.",
    "devices.title": "కనెక్ట్ అయిన డివైసులు",
    "devices.subtitle": "మానిటరింగ్ మరియు అనలిటిక్స్ కోసం కనెక్ట్ అయిన అన్ని పెస్టిసైడ్ స్ప్రే బాట్స్‌ను చూడండి.",
    "devices.multipleMonitoring": "బహుళ బాట్ మానిటరింగ్",
    "devices.readOnlyList": "చదవడానికి మాత్రమే డివైస్ జాబితా",
    "devices.active": "సక్రియ",
    "devices.offline": "ఆఫ్‌లైన్",
    "devices.connectedHwId": "కనెక్ట్ అయిన HW ID",
    "demo.noBotsTitle": "డెమో బాట్స్ అందుబాటులో లేవు",
    "demo.noBotsDesc": "డాష్‌బోర్డ్ లేఅవుట్‌ను చూడడానికి డెమో బాట్ డేటాను జోడించండి.",
    "demo.demoBots": "డెమో బాట్స్",
    "demo.demoMode": "డెమో మోడ్",
    "demo.demoModeDesc": "డిస్కనెక్ట్ చేయడానికి కనెక్ట్ అయిన డివైస్ లేదు.",
    "connect.fetchError": "అందుబాటులో ఉన్న బాట్స్‌ను తీసుకురాలేకపోయాం",
    "connect.devicePairing": "డివైస్ పేర్ింగ్",
    "connect.liveScanning": "లైవ్ స్కానింగ్",
    "connect.botDiscovery": "బాట్ డిస్కవరీ",
    "connect.searchingDesc": "మీ లోకల్ నెట్‌వర్క్‌లో నిజమైన ESP32 ఆధారిత స్ప్రే బాట్స్‌ను వెతుకుతోంది.",
    "connect.scanningTitle": "Wi-Fi లో బాట్స్‌ను స్కాన్ చేస్తోంది...",
    "connect.scanningDesc": "మీ ESP32 Wi-Fi మాడ్యూల్ ఆన్‌లో ఉందని మరియు ఇదే నెట్‌వర్క్‌కు కనెక్ట్ అయి ఉందని నిర్ధారించుకోండి.",
    "connect.availableNearby": "సమీపంలో ఉన్న డివైసులు",
    "connect.rescanNetwork": "నెట్‌వర్క్ మళ్లీ స్కాన్ చేయండి",
    "connect.hardwareId": "హార్డ్వేర్ ID: {botId}",
    "connect.signal": "సిగ్నల్",
    "connect.esp32Ready": "ESP32 సిద్ధం",
    "connect.connectNow": "ఇప్పుడే కనెక్ట్ చేయండి",
    "connect.noBotsTitle": "నిజమైన బాట్స్ కనబడలేదు",
    "connect.noBotsDesc": "మీ నెట్‌వర్క్‌లో ఎలాంటి ESP32 మాడ్యూల్ కనిపించలేదు. Wi-Fi సెట్టింగులను చెక్ చేసి మళ్లీ ప్రయత్నించండి.",
    "connect.cantFindBot": "మీ బాట్ కనబడలేదా?",
    "connect.manualDesc": "నిజమైన టెలిమెట్రీతో ధృవీకరించి కనెక్ట్ చేయడానికి డివైస్ వివరాలు నమోదు చేయండి.",
    "connect.botId": "బాట్ ID",
    "connect.botNameOptional": "బాట్ పేరు (ఐచ్ఛికం)",
    "connect.channelId": "చానెల్ ID",
    "connect.readApiKey": "రీడ్ API కీ",
    "connect.botIdPlaceholder": "బాట్ ID నమోదు చేయండి",
    "connect.botNamePlaceholder": "ఉదా. Orchard Unit",
    "connect.channelPlaceholder": "ThingSpeak చానెల్ ID",
    "connect.readKeyPlaceholder": "ThingSpeak Read API Key",
    "connect.validating": "ధృవీకరిస్తోంది...",
    "connect.validateConnect": "ధృవీకరించి కనెక్ట్ చేయండి",
    "connect.thingSpeakSetup": "ThingSpeak సెటప్",
    "connect.connectingToast": "{botId} కి కనెక్ట్ అవుతోంది...",
    "connect.connectingDesc": "సురక్షిత వ్యవసాయ టెలిమెట్రీ లింక్ స్థాపిస్తోంది.",
    "connect.syncedToast": "{botId} ఇప్పుడు సింక్ అయింది.",
    "connect.missingFields": "దయచేసి Bot ID, Channel ID, మరియు Read API Key నమోదు చేయండి",
    "connect.validationFailed": "ధృవీకరణ విఫలమైంది",
    "connect.connectionFailed": "కనెక్షన్ విఫలమైంది",
    "connect.invalidChannel": "చానెల్ ID లేదా రీడ్ API కీ చెల్లదు",
    "connect.noTelemetry": "ఈ చానెల్‌కు టెలిమెట్రీ లేదు",
    "reports.fetchError": "చారిత్రక రిపోర్ట్స్‌ను తీసుకురాలేకపోయాం",
    "reports.noReportsTitle": "రిపోర్ట్స్ అందుబాటులో లేవు",
    "reports.noReportsDesc": "మీ బాట్ మొదటి స్ప్రేయింగ్ మిషన్ పూర్తి చేసిన తర్వాత చారిత్రక అనలిటిక్స్ ఇక్కడ కనిపిస్తాయి.",
    "reports.performanceReports": "పర్ఫార్మెన్స్ రిపోర్ట్స్",
    "reports.connected": "కనెక్ట్ అయింది",
    "reports.disconnected": "డిస్కనెక్ట్ అయింది",
    "reports.operationAnalytics": "ఆపరేషన్ అనలిటిక్స్",
    "reports.operationDesc": "చారిత్రక పనితీరు డేటా మరియు వనరుల సమర్థత మెట్రిక్స్.",
    "reports.connectedBot": "కనెక్ట్ అయిన బాట్: {botId}",
    "reports.exportSoon": "PDF ఎగుమతి త్వరలో వస్తుంది.",
    "reports.totalDistance": "మొత్తం దూరం",
    "reports.totalArea": "మొత్తం ప్రాంతం",
    "reports.pesticideUsed": "వాడిన పెస్టిసైడ్",
    "reports.lastActive": "చివరిసారి సక్రియ",
    "reports.historicalPerformance": "చారిత్రక పనితీరు",
    "reports.resourceUtilization": "వనరుల వినియోగం",
    "reports.performanceInsights": "పర్ఫార్మెన్స్ ఇన్‌సైట్స్",
    "reports.insightData": "అనలిటిక్స్ {botId} నుండి వచ్చిన రియల్-టైమ్ డేటా ఆధారంగా ఉంటాయి. మరింత డేటా సేకరించబడినకొద్దీ ఇన్‌సైట్స్ రూపొందుతాయి.",
    "reports.insightEfficiency": "ప్రస్తుత సెషన్ కవరేజ్ ప్రాంతీయ ప్రమాణాలతో పోలిస్తే {percent}% వనరుల సమర్థత చూపిస్తోంది.",
    "profile.nameEmpty": "పేరు ఖాళీగా ఉండకూడదు",
    "profile.updated": "ప్రొఫైల్ అప్‌డేట్ అయింది!",
    "profile.botOwnerProfile": "బాట్ ఓనర్ ప్రొఫైల్",
    "profile.subtitle": "మీ పెస్టిసైడ్ స్ప్రేయింగ్ ఫ్లీట్ కోసం వ్యక్తిగత మానిటరింగ్ యాక్సెస్.",
    "profile.totalConnectedDevices": "మొత్తం కనెక్ట్ అయిన డివైసులు",
    "profile.monitoringAccess": "మానిటరింగ్ యాక్సెస్",
    "profile.readOnly": "చదవడానికి మాత్రమే",
    "profile.oneBot": "1 బాట్",
    "profile.zeroBots": "0 బాట్స్",
    "profile.recentActivity": "ఇటీవలి డివైస్ కార్యకలాపం",
    "profile.monitoringRecords": "మానిటరింగ్ రికార్డులు",
    "profile.deviceId": "డివైస్ ID",
    "profile.lastActiveTime": "చివరి సక్రియ సమయం",
    "profile.status": "స్థితి",
    "profile.battery": "బ్యాటరీ",
    "profile.tank": "ట్యాంక్",
    "profile.loadingTelemetry": "టెలిమెట్రీ లోడ్ అవుతోంది...",
    "profile.noTelemetry": "ఇప్పటివరకు టెలిమెట్రీ అందుబాటులో లేదు.",
    "profile.noActivityTitle": "బాట్ కార్యకలాపం నమోదు కాలేదు",
    "profile.noActivityDesc": "చారిత్రక టెలిమెట్రీ లాగ్స్ చూడడానికి డివైస్ కనెక్ట్ చేయండి.",
    "logs.fetchError": "మానిటరింగ్ లాగ్స్‌ను తీసుకురాలేకపోయాం",
    "logs.searchPlaceholder": "మానిటరింగ్ లాగ్స్‌లో శోధించండి…",
    "logs.eventType": "ఈవెంట్ రకం",
    "logs.allEvents": "అన్ని ఈవెంట్‌లు",
    "logs.telemetry": "టెలిమెట్రీ",
    "logs.task": "టాస్క్",
    "logs.tank": "ట్యాంక్",
    "logs.device": "డివైస్",
    "logs.exportSuccess": "మానిటరింగ్ లాగ్స్ CSV గా ఎగుమతి అయ్యాయి",
    "logs.timestamp": "టైమ్‌స్టాంప్",
    "logs.event": "ఈవెంట్",
    "logs.detail": "వివరాలు",
    "logs.status": "స్థితి",
    "logs.loading": "లాగ్స్ లోడ్ అవుతున్నాయి...",
    "logs.noLogs": "మానిటరింగ్ లాగ్స్ లేవు.",
    "logs.connectDevice": "లాగ్స్ చూడడానికి డివైస్ కనెక్ట్ చేయండి.",
    "logs.deviceAlert": "డివైస్ అలర్ట్",
    "logs.batteryWarning": "బ్యాటరీ హెచ్చరిక",
    "logs.tankWarning": "ట్యాంక్ హెచ్చరిక",
    "logs.telemetryUpdate": "టెలిమెట్రీ అప్‌డేట్",
    "logs.detailDistance": "దూరం {value} m",
    "logs.detailArea": "ప్రాంతం {value} acres",
    "logs.detailTank": "ట్యాంక్ {value}%",
    "logs.detailBattery": "బ్యాటరీ {value}%",
    "logs.detailReceived": "టెలిమెట్రీ అందింది",
    "notFound.title": "అయ్యో! పేజీ కనిపించలేదు",
    "notFound.returnHome": "హోమ్‌కు తిరిగి వెళ్లండి",
    "help.title": "సహాయం కావాలా?",
    "help.desc": "మీ బాట్‌లో సమస్య ఉందా? మాకు సందేశం పంపండి, మేము మీకు తిరిగి కాల్ చేస్తాము.",
    "help.phone": "మీ ఫోన్ నంబర్",
    "help.phonePlaceholder": "మీ ఫోన్ నంబర్ నమోదు చేయండి",
    "help.message": "మీ సందేశం",
    "help.messagePlaceholder": "మీ సమస్యను వివరించండి...",
    "help.submit": "సహాయ అభ్యర్థన పంపండి",
    "help.sent": "సహాయ అభ్యర్థన పంపబడింది! మేము త్వరలో మీకు కాల్ చేస్తాము.",
    "help.failed": "అభ్యర్థన పంపడం విఫలమైంది",
  },
};

const isLanguage = (value: string | null): value is Language =>
  value === "en" || value === "hi" || value === "te";

const getInitialLanguage = (): Language => {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    return isLanguage(stored) ? stored : "en";
  } catch {
    return "en";
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => getInitialLanguage());

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, language);
    } catch {
      // Ignore storage write errors.
    }
  }, [language]);

  const t = useMemo(() => {
    return (key: string, vars?: Record<string, string | number>) => {
      const template = translations[language][key] || translations.en[key] || key;
      if (!vars) return template;
      return template.replace(/\{(\w+)\}/g, (_, token) => {
        const value = vars[token];
        return value === undefined || value === null ? `{${token}}` : String(value);
      });
    };
  }, [language]);

  const value = useMemo(
    () => ({ language, setLanguage, t }),
    [language, t],
  );

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

export const languageOptions: Array<{ value: Language; label: string }> = [
  { value: "en", label: "English" },
  { value: "hi", label: "हिन्दी" },
  { value: "te", label: "తెలుగు" },
];

export type { Language };
