export const monitoredDevices = {
  device1: {
    name: "Device 1",
    id: "BOT-AG-102",
    state: "Active",
    sync: "2 min ago",
    distance: "1240",
    area: "3.6",
    pesticide: "21.3",
    time: "6.2",
    completion: "68",
    battery: 84,
    tank: 72,
    uncovered: "1.7",
    task: "In Progress",
    distanceData: [
      { time: "06:00", distance: 120 },
      { time: "07:00", distance: 340 },
      { time: "08:00", distance: 580 },
      { time: "09:00", distance: 720 },
      { time: "10:00", distance: 940 },
      { time: "11:00", distance: 1120 },
      { time: "12:00", distance: 1240 },
    ],
    pesticideData: [
      { session: "S1", liters: 3.2, duration: 45 },
      { session: "S2", liters: 4.7, duration: 62 },
      { session: "S3", liters: 3.9, duration: 51 },
      { session: "S4", liters: 5.4, duration: 74 },
      { session: "S5", liters: 4.1, duration: 58 },
    ],
    taskStatusData: [
      { name: "Completed", value: 68, color: "hsl(var(--primary))" },
      { name: "In Progress", value: 22, color: "hsl(var(--accent))" },
      { name: "Not Completed", value: 10, color: "hsl(var(--warning))" },
    ],
    report: {
      distance: "2460",
      area: "21.2",
      pesticide: "52.4",
      time: "11.2",
      history: [
        { day: "Mon", distance: 280, area: 2.7, time: 1.2 },
        { day: "Tue", distance: 340, area: 3.4, time: 1.5 },
        { day: "Wed", distance: 420, area: 3.9, time: 1.8 },
        { day: "Thu", distance: 390, area: 3.7, time: 1.6 },
        { day: "Fri", distance: 510, area: 4.4, time: 2.1 },
        { day: "Sat", distance: 320, area: 2.9, time: 1.4 },
        { day: "Sun", distance: 200, area: 1.9, time: 0.9 },
      ],
      usage: [
        { day: "Mon", liters: 6.4 },
        { day: "Tue", liters: 7.2 },
        { day: "Wed", liters: 9.1 },
        { day: "Thu", liters: 8.4 },
        { day: "Fri", liters: 10.6 },
        { day: "Sat", liters: 6.8 },
        { day: "Sun", liters: 3.9 },
      ],
      insights: ["You did the most work on Friday.", "Pesticide use is normal for this field size.", "Work is going faster than last week."],
    },
  },
  device2: {
    name: "Device 2",
    id: "BOT-AG-118",
    state: "Active",
    sync: "5 min ago",
    distance: "840",
    area: "2.1",
    pesticide: "14.8",
    time: "4.5",
    completion: "54",
    battery: 76,
    tank: 58,
    uncovered: "1.8",
    task: "Completed",
    distanceData: [
      { time: "06:00", distance: 110 },
      { time: "07:00", distance: 240 },
      { time: "08:00", distance: 390 },
      { time: "09:00", distance: 510 },
      { time: "10:00", distance: 640 },
      { time: "11:00", distance: 760 },
      { time: "12:00", distance: 840 },
    ],
    pesticideData: [
      { session: "S1", liters: 2.6, duration: 38 },
      { session: "S2", liters: 3.1, duration: 44 },
      { session: "S3", liters: 2.8, duration: 41 },
      { session: "S4", liters: 3.4, duration: 52 },
      { session: "S5", liters: 2.9, duration: 45 },
    ],
    taskStatusData: [
      { name: "Completed", value: 54, color: "hsl(var(--primary))" },
      { name: "In Progress", value: 34, color: "hsl(var(--accent))" },
      { name: "Not Completed", value: 12, color: "hsl(var(--warning))" },
    ],
    report: {
      distance: "1820",
      area: "15.8",
      pesticide: "39.8",
      time: "8.5",
      history: [
        { day: "Mon", distance: 180, area: 1.9, time: 0.8 },
        { day: "Tue", distance: 240, area: 2.2, time: 1.1 },
        { day: "Wed", distance: 310, area: 2.7, time: 1.4 },
        { day: "Thu", distance: 290, area: 2.5, time: 1.3 },
        { day: "Fri", distance: 380, area: 3.4, time: 1.6 },
        { day: "Sat", distance: 250, area: 2.2, time: 1.2 },
        { day: "Sun", distance: 170, area: 0.7, time: 0.4 },
      ],
      usage: [
        { day: "Mon", liters: 4.3 },
        { day: "Tue", liters: 5.8 },
        { day: "Wed", liters: 6.9 },
        { day: "Thu", liters: 6.2 },
        { day: "Fri", liters: 8.1 },
        { day: "Sat", liters: 5.4 },
        { day: "Sun", liters: 3.1 },
      ],
      insights: ["The bot covered about 2 acres every day.", "Pesticide use was steady all week.", "Two sessions are still being worked on."],
    },
  },
  device3: {
    name: "Device 3",
    id: "BOT-AG-125",
    state: "Offline",
    sync: "1 hr ago",
    distance: "520",
    area: "1.3",
    pesticide: "7.6",
    time: "2.1",
    completion: "41",
    battery: 49,
    tank: 44,
    uncovered: "1.9",
    task: "Completed",
    distanceData: [
      { time: "06:00", distance: 80 },
      { time: "07:00", distance: 190 },
      { time: "08:00", distance: 310 },
      { time: "09:00", distance: 440 },
      { time: "10:00", distance: 520 },
    ],
    pesticideData: [
      { session: "S1", liters: 1.8, duration: 25 },
      { session: "S2", liters: 2.3, duration: 32 },
      { session: "S3", liters: 1.6, duration: 22 },
      { session: "S4", liters: 1.9, duration: 28 },
    ],
    taskStatusData: [
      { name: "Completed", value: 41, color: "hsl(var(--primary))" },
      { name: "In Progress", value: 0, color: "hsl(var(--accent))" },
      { name: "Not Completed", value: 59, color: "hsl(var(--warning))" },
    ],
    report: {
      distance: "1180",
      area: "11.1",
      pesticide: "25.9",
      time: "5.6",
      history: [
        { day: "Mon", distance: 140, area: 1.2, time: 0.6 },
        { day: "Tue", distance: 190, area: 1.9, time: 0.9 },
        { day: "Wed", distance: 220, area: 2.2, time: 1.1 },
        { day: "Thu", distance: 170, area: 1.5, time: 0.8 },
        { day: "Fri", distance: 240, area: 2.5, time: 1.2 },
        { day: "Sat", distance: 150, area: 1.2, time: 0.7 },
        { day: "Sun", distance: 70, area: 0.5, time: 0.3 },
      ],
      usage: [
        { day: "Mon", liters: 3.2 },
        { day: "Tue", liters: 4.1 },
        { day: "Wed", liters: 4.8 },
        { day: "Thu", liters: 3.6 },
        { day: "Fri", liters: 5.3 },
        { day: "Sat", liters: 3.4 },
        { day: "Sun", liters: 1.5 },
      ],
      insights: ["The bot is currently turned off.", "Most work was done before it went offline.", "Check the pesticide tank before the next run."],
    },
  },
  device4: {
    name: "Device 4",
    id: "BOT-AG-131",
    state: "Active",
    sync: "9 min ago",
    distance: "760",
    area: "1.8",
    pesticide: "10.9",
    time: "3.4",
    completion: "47",
    battery: 68,
    tank: 62,
    uncovered: "2.0",
    task: "In Progress",
    distanceData: [
      { time: "06:00", distance: 100 },
      { time: "07:00", distance: 220 },
      { time: "08:00", distance: 340 },
      { time: "09:00", distance: 460 },
      { time: "10:00", distance: 580 },
      { time: "11:00", distance: 680 },
      { time: "12:00", distance: 760 },
    ],
    pesticideData: [
      { session: "S1", liters: 2.0, duration: 29 },
      { session: "S2", liters: 2.6, duration: 35 },
      { session: "S3", liters: 2.1, duration: 31 },
      { session: "S4", liters: 2.4, duration: 34 },
      { session: "S5", liters: 1.8, duration: 27 },
    ],
    taskStatusData: [
      { name: "Completed", value: 47, color: "hsl(var(--primary))" },
      { name: "In Progress", value: 38, color: "hsl(var(--accent))" },
      { name: "Not Completed", value: 15, color: "hsl(var(--warning))" },
    ],
    report: {
      distance: "1550",
      area: "14.3",
      pesticide: "32.6",
      time: "7.8",
      history: [
        { day: "Mon", distance: 160, area: 1.5, time: 0.7 },
        { day: "Tue", distance: 210, area: 1.9, time: 1.0 },
        { day: "Wed", distance: 270, area: 2.5, time: 1.3 },
        { day: "Thu", distance: 240, area: 2.2, time: 1.2 },
        { day: "Fri", distance: 310, area: 2.9, time: 1.5 },
        { day: "Sat", distance: 220, area: 1.9, time: 1.1 },
        { day: "Sun", distance: 140, area: 1.2, time: 0.6 },
      ],
      usage: [
        { day: "Mon", liters: 3.8 },
        { day: "Tue", liters: 4.6 },
        { day: "Wed", liters: 5.5 },
        { day: "Thu", liters: 5.0 },
        { day: "Fri", liters: 6.4 },
        { day: "Sat", liters: 4.5 },
        { day: "Sun", liters: 2.8 },
      ],
      insights: ["Field coverage looks good and steady.", "Pesticide use is correct for the area sprayed.", "The bot is still working on the current task."],
    },
  },
};

export type DeviceKey = keyof typeof monitoredDevices;
export const monitoredDeviceList = Object.values(monitoredDevices);
